package model;

import util.PatchPattern;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/*
Represents one square block of a quilt with a name, a finished size (in inches), and a list of patches
The list of patches is automatically generated by the PatchPattern util class based on the name of the block entered
*/

public class Block {

    public static final String[] AVAILABLE_BLOCKS = {"friendship star", "greek square", "checkerboard"};
    private static final int NUM_OF_PATCHES = 9;

    private String name;
    private double finishedSize;
    private List<Patch> patches;

    // REQUIRES: finishedSize > 0, name must be in AVAILABLE_BLOCKS
    // EFFECTS: creates a block (list of patches) of the given name and of the given finished side length (in inches)
    public Block(String name, double finishedSize) {
        this.name = name;
        this.finishedSize = finishedSize;

        PatchPattern pattern = new PatchPattern();
        this.patches = pattern.getPattern(name, getFinishedPatchSize());
    }

    // getters
    public String getName() {
        return name;
    }

    public double getFinishedSize() {
        return finishedSize;
    }

    public List<Patch> getPatches() {
        return patches;
    }

    // EFFECTS: calculates the finished side length (in inches) of each patch that comprises the block
    public double getFinishedPatchSize() {
        return finishedSize / Math.sqrt(NUM_OF_PATCHES);
    }

    // EFFECTS: counts the number of patches of the given type needed to make the block
    public double countPatches(String patchType) {
        int count = 0;
        for (Patch p : patches) {
            if (p.getType().equals(patchType)) {
                count += 1;
            }
        }
        return count;
    }

    // EFFECTS: calculates the amount of fabric (in square inches) needed of the given type to create the block
    public double calculateFabric(String fabric) {
        double total = 0;
        for (Patch p : patches) {
            if (p.containsFabric(fabric)) {
                total += p.calculateFabric(fabric);
            }
        }
        return total;
    }

}

